[project]
name = "microescrow"
description = "Unique voting contract for project 04"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.microescrow]
path = "contracts/microescrow.clar"

[repl.analysis]
passes = ["check_checker"]
